# Generated by Django 2.2.13 on 2021-03-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailsuser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='detailsuser',
            name='user_location',
        ),
        migrations.AddField(
            model_name='detailsuser',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detailsuser',
            name='u_firstname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detailsuser',
            name='u_lastname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detailsuser',
            name='username',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
