# Generated by Django 2.2.13 on 2021-04-08 12:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uapp', '0002_auto_20210312_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatsUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, null=True, unique=True)),
                ('otherperson_username', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None)),
            ],
            options={
                'db_table': 'chats',
            },
        ),
    ]
