# Generated by Django 2.2.13 on 2021-04-12 11:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uapp', '0003_chatsuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsuser',
            name='otherperson_username',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='chatsuser',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
